


#' Create bar graphs of winner's margin per district by percent or raw votes
#'
#' @param election_df data frame of election results generated by wrangle_results()
#' @param district_col name of the election district column NOT in quotation marks
#' @param margin_col name of the column with percent or vote margins NOT in quotation marks
#' @param headline  character string for desired graph headline, defaults to ""
#' @param palette character string of hex colors for winner, loser, and ties
#' @param winner_col name of column with the winner for each district NOT in quotation marks, defaults to Winner
#' @param theme ggplot theme function. Defaults to theme_minimal() but allows for easy change of theme while still using function.
#' @param order_bars_desc logical should bars be ordered by descending value? Defaults to FALSE
#'
#' @return ggplot object
#' @export
#' @examples
#' my_election_results <- wrangle_results(system.file("extdata", "FakeElectionResults.xlsx", package = "elections2")) %>%
#' dplyr::filter(Precinct != "Total")
#' bargraph_of_margins(my_election_results, Precinct, Yes_Pct_Margin, order_bars_desc = TRUE, headline = "Yes Margins by Precinct")
#'
bargraph_of_margins <- function(election_df, district_col, margin_col, headline = "", palette = c("#9970ab", "#5aae61", "#f7f7f7"), winner_col = Winner, theme = theme_minimal(), order_bars_desc = FALSE) {

 if(order_bars_desc) {
   district_col_name <- deparse(substitute(district_col))
   election_df[[district_col_name]] <- as.character(election_df[[district_col_name]])
   election_df[[district_col_name]] <- factor(election_df[[district_col_name]], levels = unique(election_df[[district_col_name]][order(election_df[[6]], decreasing = TRUE)], ordered = TRUE))
 }

  the_graph <- ggplot(election_df, aes(x={{district_col}}, y = {{margin_col}},  fill = {{winner_col}})) +
    geom_col(color = "black") +
    theme +
    ylab("") +
    scale_fill_manual(values = palette) +
    ggtitle(headline)
  return(the_graph)

}

