


#' Create bar graphs of winner's margin per district by percent or raw votes
#'
#' This function expects data in the format generated by the wrangle_results() or wrangle_more_cols() functions.
#'
#'
#' @param election_df data frame of election results generated by wrangle_results() or wrangle_more_cols()
#' @param district_col name of the election district column NOT in quotation marks
#' @param margin_col name of the column with percent or vote margins NOT in quotation marks
#' @param headline  character string for desired graph headline, defaults to ""
#' @param palette if brewer_palette is FALSE, character string of hex colors for winner, loser, and ties
#' if brewer palette is TRUE, character string with RColorBrewer palette name or integer with palette number.
#'
#' @param brewer_palette logical if TRUE use an RColorBrewer palette
#' @param winner_col name of column with the winner for each district NOT in quotation marks, defaults to Winner.
#' @param theme ggplot theme function. Defaults to theme_minimal() but allows for easy change of theme while still using function.
#' @param order_bars_desc logical should bars be ordered by descending value? Defaults to FALSE
#'
#' @return ggplot object
#' @export
#' @examples
#' my_file <- system.file("extdata", "FakeElectionResults.xlsx", package = "elections2")
#' my_election_results <- wrangle_results(my_file)
#' bargraph_of_margins(my_election_results, Precinct, Yes_Pct_Margin, order_bars_desc = TRUE, headline = "Yes Margins by Precinct")


bargraph_of_margins <- function(election_df, district_col, margin_col, headline = "", palette = c("#9970ab", "#5aae61", "#f7f7f7"), brewer_palette = FALSE, winner_col = Winner, theme = theme_minimal(), order_bars_desc = FALSE ) {


 if(order_bars_desc) {
   district_col_name <- deparse(substitute(district_col))
   election_df[[district_col_name]] <- as.character(election_df[[district_col_name]])
   election_df[[district_col_name]] <- factor(election_df[[district_col_name]], levels = unique(election_df[[district_col_name]][order(election_df[[6]], decreasing = TRUE)], ordered = TRUE))
 }

  election_df <- election_df[election_df[[1]] != "Total",]
  the_graph <- ggplot(election_df, aes(x={{district_col}}, y = {{margin_col}},  fill = {{winner_col}})) +
    geom_col(color = "black") +
    theme_minimal() +
    theme(legend.title=element_blank()) +
    ylab("") +
    ggtitle(headline)

  if(!brewer_palette) {
    the_graph <- the_graph +
      scale_fill_manual(values = palette)
  } else {
    the_graph <- the_graph +
      scale_fill_brewer(type = "qual", palette = palette)

  }

  return(the_graph)

}

