


#' Create a quick searchable, sortable table of results
#'
#' Features colored bars in percent columns
#'
#' @param election_df data frame of election results generated by wrangle_results()
#' @param win_col_name character string with name of winning candidate/issue, either column 2 or 3 in data frame
#' @param pagination integer how many rows to display on each color
#' @param win_color character string for color bar in winner's percent column, defaults to "#c2a5cf" (a light purple)
#' @param lose_color character string for color bar in winner's percent column, defaults to "#a6dba0" (a light green)
#' @param use_regex_searching logical whether to allow searching by regular expression, defaults to TRUE
#'
#' @return html widget with interactive table of results
#' @export
#'
#' @examples
#' my_election_results <- wrangle_results(system.file("extdata", "FakeElectionResults.xlsx", package = "elections2"))
#' quick_table(my_election_results, "Marcy")
quick_table <- function(election_df, win_col_name, pagination = 20, win_color = "#c2a5cf", lose_color = "#a6dba0", use_regex_searching = TRUE) {
  candidates <- names(election_df)[1:3]
  election_district_col_name <- candidates[1]
  if(candidates[2] != win_col_name) {
    data.table::setcolorder(election_df, c(1,3,2))
  }
  win_pct_col_name <- paste0(win_col_name, "_Pct")
  lose_pct_col_name <- paste0(names(election_df)[3], "_Pct")

  the_table <- DT::datatable(election_df[, c(1:7)], rownames = FALSE, filter = 'top',
                             class = "stripe cell-border hover",
                             options = list(
                               pageLength = pagination,
                               search = list(regex = use_regex_searching)
                             )) %>%
    DT::formatCurrency(c(2,3,4,8), currency = '', digits = 0) %>%
    DT::formatPercentage(6:7, digits = 1) %>%
    DT::formatStyle(win_pct_col_name,
                    background = DT::styleColorBar( c(0,1), win_color),
                    backgroundSize = '98% 88%',
                    backgroundRepeat = 'no-repeat',
                    backgroundPosition = 'center'
    ) %>%
    DT::formatStyle(lose_pct_col_name,
                    background = DT::styleColorBar( c(0,1), lose_color),
                    backgroundSize = '98% 88%',
                    backgroundRepeat = 'no-repeat',
                    backgroundPosition = 'center'
    )

  return(the_table)

}
