


#' Generate table of results with more than 2 columns, including sparkline bar graphs for percent data
#'
#' @param election_df data table of election results generated by wrangle_more_cols() function
#' @param graph_cols vector of character strings with names of columns containing vote or percent results
#' @param num_format character string either "pct" or "votes" - whether election_df contains vote totals or percents
#' @param pagination integer number of rows to display per page, defaults to 20
#'
#' @return
#' @export
#'
#' @examples
#' myfile <- system.file("extdata", "Fake3Columns.xlsx", package = "elections2")
#' mydt <- wrangle_more_cols(myfile, c("Red", "Blue", "Orange", "Green", "Purple"))
#' quick_table_more_cols(mydt, c("Red", "Blue", "Orange", "Green", "Purple"))

quick_table_more_cols <- function(election_df, graph_cols, num_format = "pct", pagination = 20) {


  # PERCENT

  if(num_format == "pct") {

    election_df$Results <- NA

    for(i in 1:nrow(election_df)){
      election_df$Results[i] <- list(as.numeric(election_df[i, graph_cols]))
    }

    max_bar <- max(election_df[graph_cols], na.rm = TRUE)

  reactable::reactable(election_df, bordered = TRUE, searchable = TRUE,
                       showSortable = TRUE, showSortIcon = TRUE,
                       defaultColDef = reactable::colDef(
                         headerStyle = list(background = "#f7f7f8"),
                         format = reactable::colFormat(percent = TRUE, digits = 1)
                       ),
                       columns = list(
                         Results = reactable::colDef(cell = function(values) {
                           sparkline::sparkline(values, type = "bar", chartRangeMin = 0, chartRangeMax = max_bar)
                         })
                       ),
                       defaultPageSize = pagination
  )

} else {

  # VOTES
  reactable::reactable(election_df, bordered = TRUE, searchable = TRUE,
                       showSortable = TRUE, showSortIcon = TRUE,
                       defaultColDef = reactable::colDef(
                         headerStyle = list(background = "#f7f7f8"),
                         format = reactable::colFormat(separators = TRUE)
                       ),
                       defaultPageSize = pagination
  )

}

}
